apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: {{ .Values.addtask.replicas }}
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
          - name: CONNECTION_STRING
            value: {{ .Values.addtask.value }}
        image: {{ .Values.addtask.image }}
        ports:
        - containerPort: 8000
