apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
spec:
  replicas: {{.Values.gettask.replicas }}
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      containers:
      - name: get-tasks
        env:
          - name: CONNECTION_STRING
            value: {{.Values.gettask.value }}                                         
        image: {{.Values.gettask.image }}
        ports:
        - containerPort: 8000
