addtask:
  replicas: 2
  image: acrtodoappsiddharth1.azurecr.io/addtask:13
  value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:siddharthsql75785767675.database.windows.net,1433;Database=siddharthdb-dev;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  host: devadd.6weathers.com
deletetask:
  replicas: 2
  image: acrtodoappsiddharth1.azurecr.io/deletetask:8
  value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:siddharthsql75785767675.database.windows.net,1433;Database=siddharthdb-dev;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  host: devdelete-task.6weathers.com
gettask:
   replicas: 2
   image: acrtodoappsiddharth1.azurecr.io/gettask:6
   value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:siddharthsql75785767675.database.windows.net,1433;Database=siddharthdb-dev;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
   host: devget-tasks.6weathers.com
uitodo:
   replicas: 2
   image: acrtodoappsiddharth1.azurecr.io/uitask:4
   host: devui.6weathers.com
