apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-task
spec:
  replicas: {{ .Values.deletetask.replicas }}
  selector:
    matchLabels:
      app: delete-task
  template:
    metadata:
      labels:
        app: delete-task
    spec:
      containers:
      - name: delete-task
        env:
          - name: CONNECTION_STRING
            value: {{ .Values.deletetask.value }}
        image: {{ .Values.deletetask.image }}
        ports:
        - containerPort: 8000
